"""Change tags field from ARRAY to String

Revision ID: 0aee2fc93ba4
Revises: e52bee715979
Create Date: 2025-02-20 14:28:12.830168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aee2fc93ba4'
down_revision: Union[str, None] = 'e52bee715979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
