"""Fixed completed default

Revision ID: 831cc0532a07
Revises: 3d12d6bd2a75
Create Date: 2025-02-19 00:52:36.465151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831cc0532a07'
down_revision: Union[str, None] = '3d12d6bd2a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
