"""Change tags field from ARRAY to String in Task model

Revision ID: b96ceba83f5d
Revises: e3ea33b535ae
Create Date: 2025-02-20 14:19:33.095759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96ceba83f5d'
down_revision: Union[str, None] = 'e3ea33b535ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
