"""Added AI-generated task tagging

Revision ID: e3ea33b535ae
Revises: 52337b338752
Create Date: 2025-02-19 09:25:36.385142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ea33b535ae'
down_revision: Union[str, None] = '52337b338752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('tasks', 'tags')
    # ### end Alembic commands ###
